# Generated by Django 3.2.3 on 2021-05-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecogitoAnnotation',
            fields=[
                ('re_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('re_text', models.TextField(blank=True, null=True)),
                ('re_start', models.IntegerField(blank=True, null=True)),
                ('re_end', models.IntegerField(blank=True, null=True)),
                ('re_payload', models.JSONField(blank=True, null=True)),
                ('re_app', models.CharField(blank=True, max_length=100, null=True)),
                ('re_model', models.CharField(blank=True, max_length=100, null=True)),
                ('re_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('re_field_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
