name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: coverage run manage.py test
    - name: Create Coverage Report
      run: coverage xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true